### ISSUE TITLE
snapshot not work

### ISSUE THREAD

**Issue by mariofraga** [dji-sdk/Tello-Python#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "D:\Desenvolvimento\tello\Tello-Python-master\Tello_Video\tello_control_ui.py", line 245, in takeSnapshot
    cv2.imwrite(p, cv2.cvtColor(self.frame, cv2.COLOR_RGB2BGR))
error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by potofpie** [comment]
Did anyone find a solution to this open cv problem? Is the wrong version installed?
