### ISSUE TITLE
Error when Snapshot (Ubuntu 18.04)

### ISSUE THREAD

**Issue by sunxt99** [dji-sdk/Tello-Python#46]
I follow the steps but failed to take snapshot. I try every method but it don't work. Thx for help.
-------------------------------------------------------------------------------------
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1550, in __call__
    return self.func(*args)
  File "/home/sxt17/Desktop/Tello-Python/Tello_Video/tello_control_ui.py", line 245, in takeSnapshot
    cv2.imwrite(p, cv2.cvtColor(self.frame, cv2.COLOR_RGB2BGR))
error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by dji-dev** [comment]
Public comment from Ho.Yan in <a href='https://djisdksupport.zendesk.com/agent/tickets/29907'>Zendesk ticket #29907</a>:<br><br>Dear developer,

Hi, thanks for your connect us.

Under normal circumstances, in the case of tello wifi is already connected, the GUI will pop up the video stream after running the program, and can use the snapshot button normally to take pictures if it is not working properly
  Consider and check for the following:
  a. Whether your PC device is properly connected to your tello wifi;
  b. Check your PC's network firewall, which may block video streaming data;
  c. Further check your network settings, because tello is the PC's 11111 port video stream data push, so check to see if your network settings disable the 11111UDP port, or the 11111 port of UDP data was blocked.
    If so, undisable;
  d. In rare cases, it is possible that the 'streamon' instruction sent by the PC has lost the packet and has not been received by tello, for which case, try re-running the program.

Thank you very much for your understanding and cooperation, I wish you a happy life!

Regards,

RYZE TECHNICAL SUPPORT
