### ISSUE TITLE
【Tello_Video_With_Pose_Recognition】AttributeError: 'module' object has no attribute 'dnn'

### ISSUE THREAD

**Issue by Gardenia-Ho** [dji-sdk/Tello-Python#84]
I can't download the file "pose_iter_160000.caffemodel", so I found the file on the Internet and copied it to the document. But when I ran the project, it couldn't work.

sent: command
sent: streamon
Traceback (most recent call last):
  File "F:/pycode/Tello-Python/Tello_Video_With_Pose_Recognition/main.py", line 14, in <module>
    main()
  File "F:/pycode/Tello-Python/Tello_Video_With_Pose_Recognition/main.py", line 8, in main
    vplayer = TelloUI(drone,"./img/")
  File "F:\pycode\Tello-Python\Tello_Video_With_Pose_Recognition\tello_control_ui.py", line 43, in __init__
    self.my_tello_pose = Tello_Pose()
  File "F:\pycode\Tello-Python\Tello_Video_With_Pose_Recognition\tello_pose.py", line 29, in __init__
    self.net = cv2.dnn.readNetFromCaffe(self.protoFile, self.weightsFile)
AttributeError: 'module' object has no attribute 'dnn'
![微信图片_20220301134051](https://user-images.githubusercontent.com/53643677/156111723-e221b4d5-e5d6-4d96-9956-45f9feb9aea4.png)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60883'>Zendesk ticket #60883</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/60883'>Zendesk ticket #60883</a>:<br><br>Since Python has officially stopped the maintenance of Python 2.7 version, and the DJI also has stopped the maintenance of Tello SDK python 2.7 sample, there may be some system compatibility problems, sorry for the inconvenience.

About tello sdk developer documentations, below link is for your reference( and there`s sample in the link ).

Normal white tello:
https://terra-1-g.djicdn.com/2d4dce68897a46b19fc717f3576b7c6a/Tello%20%E7%BC%96%E7%A8%8B%E7%9B%B8%E5%85%B3/For%20Tello/Tello%20SDK%20Documentation%20EN_1.3_1122.pdf

Tello EDU version:
https://dl-cdn.ryzerobotics.com/downloads/Tello/Tello%20SDK%202.0%20User%20Guide.pdf
https://robomaster-dev.readthedocs.io/en/latest/python_sdk/beginner_drone.html
https://robomaster-dev.readthedocs.io/en/latest/python_sdk/downloads.html

TT version:
https://dl.djicdn.com/downloads/RoboMaster+TT/Tello_SDK_3.0_User_Guide_en.pdf
https://robomaster-dev.readthedocs.io/en/latest/python_sdk/beginner_drone.html
https://robomaster-dev.readthedocs.io/en/latest/python_sdk/downloads.html

Tello EDU & TT version could use the Robomaster SDK, the link has attached above.
<br><p><em><small>°°°</small></em></p>
